import blogCatalog from './data/independent-blogs.json';
import type { Entry, Source } from './model';
import { t } from './i18n';
export const blogCatalogSource = blogCatalog.source;
export const blogCatalogRevision = blogCatalog.revision;

const BUILT_IN_FEED_URLS = new Set(['https://blog.qiaomu.ai/feed.xml']);
export const categories = ['全部', 'AI 与技术', '产品与工具', '人文与生活'] as const;
export type DiscoveryCollection = 'featured' | 'blogs' | 'wechat' | 'podcast';
export interface DiscoveryFeed {
  id: string;
  name: string;
  description: string;
  category: typeof categories[number] | '独立博客' | '微信公众号' | '播客';
  language: '中文' | '英文';
  icon: string;
  url: string;
  site?: string;
  tags?: string[];
}

// Curated metadata only. Opening/searching the catalog never requests these feeds.
// Source provenance and live verification: docs/DISCOVERY.md.
export const discoveryFeeds: DiscoveryFeed[] = [
  { id: 'trend-weekly', name: '潮流周刊 · Tw93', description: '每周分享科技、产品、开源项目与生活灵感。', category: '产品与工具', language: '中文', icon: 'sparkles', url: 'https://weekly.tw93.fun/rss.xml', site: 'https://weekly.tw93.fun/' },
  { id: 'ruanyifeng', name: '阮一峰的网络日志', description: '科技爱好者周刊、开发教程与长期技术观察。', category: 'AI 与技术', language: '中文', icon: 'code-xml', url: 'https://www.ruanyifeng.com/blog/atom.xml', site: 'https://www.ruanyifeng.com/blog/' },
  { id: 'codingnow', name: '云风的 BLOG', description: '游戏开发、系统设计与工程实践的一手记录。', category: 'AI 与技术', language: '中文', icon: 'gamepad-2', url: 'https://blog.codingnow.com/atom.xml', site: 'https://blog.codingnow.com/' },
  { id: 'hecaitou', name: '槽边往事 · 和菜头', description: '日常见闻、文化观察与个人经验写作。', category: '人文与生活', language: '中文', icon: 'feather', url: 'https://www.hecaitou.com/feeds/posts/default?alt=rss', site: 'https://www.hecaitou.com/' },
  { id: 'zhangxinxu', name: '张鑫旭的技术作品', description: '持续更新的 Web 前端技术研究、实验与写作。', category: 'AI 与技术', language: '中文', icon: 'braces', url: 'https://www.zhangxinxu.com/wordpress/feed/', site: 'https://www.zhangxinxu.com/' },
  { id: 'appinn', name: '小众软件', description: '发现实用、有趣、值得长期使用的软件与工具。', category: '产品与工具', language: '中文', icon: 'app-window', url: 'https://www.appinn.com/feed/', site: 'https://www.appinn.com/' },
  { id: 'williamlong', name: '月光博客', description: '互联网产品、网站技术与数字生活的长期记录。', category: 'AI 与技术', language: '中文', icon: 'moon', url: 'https://www.williamlong.info/rss.xml', site: 'https://www.williamlong.info/' },
  { id: 'reorx', name: 'Reorx’s Forge', description: '软件开发、生产力工具与数字生活的独立思考。', category: '产品与工具', language: '中文', icon: 'hammer', url: 'https://reorx.com/feed.xml', site: 'https://reorx.com/' },
  { id: 'pseudoyu', name: 'pseudoyu', description: '技术实践、个人成长与生活周报，完整记录思考过程。', category: '人文与生活', language: '中文', icon: 'notebook-pen', url: 'https://www.pseudoyu.com/zh/index.xml', site: 'https://www.pseudoyu.com/zh/' },
];
// Public RSS generated by weread-feed. These are suggestions, never auto-subscribed.
export const wechatFeeds: DiscoveryFeed[] = [
  ['qiaomu', '向阳乔木推荐看', '3008229483', 'AI 产品与工具实测，也聊模型进展和使用体验。'],
  ['zangai', '葬AI', '3988614169', '从产品和文化视角，评论 AI 模型与创业话题。'],
  ['agentju', 'AGENT橘', '3903697567', '关注 AI Agent、新模型，以及技术如何改变日常工作。'],
  ['cyberzen', '赛博禅心', '3934419561', '追踪 AI 产品、机器人与技术落地现场。'],
  ['kazike', '数字生命卡兹克', '3223096120', '实测 AI 工具和模型，分享具体用法与体验。'],
  ['latepost', '晚点LatePost', '3572959446', '报道科技与商业公司，观察产品和产业变化。'],
  ['xinzhiyuan', '新智元', '3271041950', '追踪人工智能研究、模型动态与产业新闻。'],
  ['elsewhere', 'elsewhere别处发生', '3635075805', '记录 AI、艺术与科技文化的交汇。'],
].map(([id, name, number, description]) => ({
  id: `wechat-${id}`, name, description,
  category: '微信公众号', language: '中文', icon: 'rss',
  url: `https://rss.t5t6.com/weread/MP_WXS_${number}.xml`,
}));
// Mirrors the curated shows in QMReader's podcast discovery dialog.
export const podcastRecommendations = [
  { name: 'Lex Fridman Podcast', nameZh: '莱克斯·弗里德曼播客', sourceId: 'lexfridman', slug: 'lex-fridman-podcast-artificial-intelligence-ai', description: '与科学家、技术人和各领域嘉宾长谈 AI、科学与人生。' },
  { name: 'All-In Podcast', nameZh: 'All-In 商业科技播客', sourceId: 'podscribe-all-in-with-chamath-jason-sacks-friedberg', slug: 'all-in-with-chamath-jason-sacks-friedberg', description: '四位主持人讨论商业、科技、社会与公共议题。' },
  { name: 'Acquired', nameZh: '收购秘史', sourceId: 'podscribe-acquired', slug: 'acquired', description: '深挖知名公司的发展历史与商业战略。' },
  { name: 'Pivot', nameZh: '科技与商业转向', sourceId: 'podscribe-pivot', slug: 'pivot', description: 'Kara Swisher 与 Scott Galloway 评论科技、商业和政治新闻。' },
  { name: 'Invest Like the Best', nameZh: '向顶尖投资者学习', sourceId: 'podscribe-invest-like-the-best', slug: 'invest-like-the-best', description: 'Patrick O’Shaughnessy 与嘉宾探索投资、商业和技术。' },
  { name: 'Masters of Scale', nameZh: '规模化大师', sourceId: 'podscribe-masters-of-scale', slug: 'masters-of-scale', description: '与创业者和企业领导者探讨公司成长的经验与挑战。' },
  { name: 'The Diary Of A CEO', nameZh: '一位 CEO 的日记', sourceId: 'podscribe-the-diary-of-a-ceo-with-steven-bartlett', slug: 'the-diary-of-a-ceo-with-steven-bartlett', description: 'Steven Bartlett 对话企业家、专家与创作者，聊他们的经历和思考。' },
  { name: 'The Prof G Pod', nameZh: 'G 教授播客', sourceId: 'podscribe-the-prof-g-pod-with-scott-galloway', slug: 'the-prof-g-pod-with-scott-galloway', description: 'Scott Galloway 分析商业与科技，并与嘉宾对谈。' },
  { name: 'Freakonomics Radio', nameZh: '魔鬼经济学电台', sourceId: 'podscribe-freakonomics-radio', slug: 'freakonomics-radio', description: '用经济学与采访探索日常现象背后的原因。' },
  { name: 'The Joe Rogan Experience', nameZh: '乔·罗根体验', sourceId: 'podscribe-the-joe-rogan-experience', slug: 'the-joe-rogan-experience', description: 'Joe Rogan 与科学家、作者、艺人等嘉宾进行长篇对谈。' },
] as const;
export function xiaoyuzhouPodcasts(sources: Source[]): Source[] {
  return sources.filter(source => {
    if (source.category !== 'podcast' || source.enabled === false || !source.siteUrl) return false;
    try { return new URL(source.siteUrl).hostname === 'www.xiaoyuzhoufm.com'; }
    catch { return false; }
  });
}
const featuredXiaoyuzhouIds = ['zhangxiaojun', 'nexttoken', '42zhangjing', 'latetalk', 'bannatie'] as const;
const hiddenQiaomuChannelIds = new Set(['wechat-bestblogs-2d790e38f8af54c5af77fa5fed687a7c66d34c22', 'levelingup']);
// Reader may register a visitor's WeChat subscription as a shared source.
// Only editorial picks belong in the plugin's public Qiaomu Channels section.
const featuredWechatChannelIds = new Set([
  'wechat-qiaomu', 'wechat-agentju', 'wechat-cyberzen', 'wechat-kazike',
  'wechat-latepost', 'wechat-xinzhiyuan', 'wechat-elsewhere', 'wechat-zangai',
  'wechat-bestblogs-1c3e3571b1627d23ee9c64521a0b0a41d3fe2987',
  'wechat-bestblogs-9645a69180041ff935c458753174fa8bc2061295',
]);
export function featuredXiaoyuzhouPodcasts(sources: Source[]): Source[] {
  const available = new Map(xiaoyuzhouPodcasts(sources).map(source => [source.id, source]));
  return featuredXiaoyuzhouIds.map(id => available.get(id)).filter((source): source is Source => !!source);
}
export function readerChannelSources(sources: Source[]): Source[] {
  const featuredIds = new Set(featuredXiaoyuzhouPodcasts(sources).map(source => source.id));
  return sources.filter(source => source.enabled !== false && !hiddenQiaomuChannelIds.has(source.id) &&
    (!source.id.startsWith('wechat-') || featuredWechatChannelIds.has(source.id)) &&
    (source.category !== 'podcast' || featuredIds.has(source.id)));
}
const newsletterSourceIds = new Set([
  'james-clear', 'bensbites', 'levelingup', 'tldrai', 'importai', 'nlp-elvis', 'interconnects',
  'brainfood', 'oneusefulthing', 'whytryai', 'chinai', 'dankoe', 'tylerfolkman',
  'superhuman_ai', 'aibreakfast', 'garymarcus', 'dwarkesh', 'experimental-history',
  'construction-physics', 'ds-ai-section',
]);
export const qiaomuDividers = ['微信公众号', '小宇宙', 'YouTube', 'Newsletter', '资讯', '博客与网站'] as const;
export const qiaomuDividerIcons: Record<string, string> = { 微信公众号: 'message-circle', 小宇宙: 'podcast', YouTube: 'tv', Newsletter: 'mail', 资讯: 'newspaper', 博客与网站: 'globe' };
export function qiaomuChannelDivider(source: Source): string {
  let host = '';
  try { host = new URL(source.siteUrl || '').hostname.toLowerCase(); } catch { /* Some feeds have no site URL. */ }
  if (host === 'mp.weixin.qq.com' || source.id.startsWith('wechat-')) return '微信公众号';
  if (host === 'www.xiaoyuzhoufm.com') return '小宇宙';
  if (host === 'youtube.com' || host === 'www.youtube.com' || host === 'youtu.be') return 'YouTube';
  if (newsletterSourceIds.has(source.id)) return 'Newsletter';
  if (source.category === 'news') return '资讯';
  return '博客与网站';
}
const entryTime = (entry: Entry) => entry.publishedTs || Date.parse(entry.published || '') || 0;
/** Newest first; the sort is stable, so undated entries keep their server order among themselves. */
const byNewest = (entries: Entry[]) => [...entries].sort((a, b) => entryTime(b) - entryTime(a));
/**
 * Mixes each featured show's latest episode into the 全部精选 timeline by date. An episode older than the oldest loaded
 * article waits until “加载更早文章” reaches its date (or the feed is complete), so it never lands out of order at the bottom.
 */
export function mergeFeaturedPodcasts(entries: Entry[], episodes: Entry[], complete: boolean): Entry[] {
  const times = entries.map(entryTime).filter(Boolean), oldest = times.length ? Math.min(...times) : 0;
  const due = episodes.filter(episode => complete || !times.length || entryTime(episode) >= oldest);
  return byNewest([...new Map([...due, ...entries].map(entry => [entry.id, entry])).values()]);
}
export function qiaomuFeaturedEntries(entries: Entry[]): Entry[] {
  return byNewest(entries.filter(entry => entry.sourceId !== 'allin' && entry.sourceId !== 'podscribe-all-in-with-chamath-jason-sacks-friedberg'));
}
export const independentBlogs: DiscoveryFeed[] = blogCatalog.items
  .filter(blog => !BUILT_IN_FEED_URLS.has(blog.url))
  .map(blog => ({ ...blog, description: blog.tags.join(' · ') || t('discovery.blogFallbackDesc'), category: '独立博客', language: '中文', icon: 'notebook-pen' }));
export const blogTags = [...new Set(independentBlogs.flatMap(blog => blog.tags ?? []))].sort((a, b) => a.localeCompare(b, 'zh'));

export function filterDiscovery(query: string, category: string, collection: DiscoveryCollection = 'featured', tag = ''): DiscoveryFeed[] {
  const terms = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  const source = collection === 'blogs' ? independentBlogs : collection === 'wechat' ? wechatFeeds : collection === 'podcast' ? [] : discoveryFeeds;
  return source.filter(feed => (collection === 'blogs' ? !tag || feed.tags?.includes(tag) : collection === 'wechat' || category === '全部' || feed.category === category)
    && terms.every(term => `${feed.name} ${feed.description} ${feed.category} ${feed.language} RSS Atom ${feed.site ?? ''} ${feed.url}`.toLocaleLowerCase().includes(term)));
}
